### ISSUE TITLE
Validar CNPJ de Filial

### ISSUE THREAD

**Issue by sigaocaue** [codeedu/code_validator#1]
Pessoal, tudo bom?,

Seguinte, o validator de vocês não tem como validar FILIAL, cnpjs do tipo:
XX.XXX.XXX/0002-XX
XX.XXX.XXX/0003-XX

Números 0002, 0003, até 9999. Sabe dizer se vão implementar esse tipo de validação?

**Comment by argentinaluiz** [comment]
Olá @caueprado0. A validação é específica para os dígitos verificadores. Se for uma filial e os dois últimos dígitos não baterem, será inválido, entendeu?

**Comment by sigaocaue** [comment]
Nossa como eu sou burro, kkkkkk; Funcionou, eu usei um CNPJ de uma Filial que realmente existe e passou na validação normalmente.

Obrigado Luis, sempre me salvando!
